### PR TITLE
Implement basic threads/coroutines and fix broken backwards compatability with legacy LP scripts

### PR DESCRIPTION
**Pull request by JayMontana36**

### CODE REVIEW

**Comment by JayMontana36** [comment]
Accidental request sorry

**Comment by gallexme** [comment]
oh wow didnt knew people even used luaplugin   in the last 7 years
would you like to take ownership of the github repo ? @JayMontana36

**Comment by JayMontana36** [comment]
Oh yeah there're _plenty_ of people who currently use Lua Plugin, I've been using it for a few years now after having departed from FiveM to singleplayer and then missing a lot of the scripts that I had created and/or used at the time, alongside how quickly and easily I could write a working and efficient script without the need to compile or anything like that (not to mention I don't know/understand any C to be able to do anything with it), then I decided to fork it a little bit over a year ago so that I could share my improvements and enhancements and hopefully revive the use and viability of Lua in GTA outside of FiveM. Your version however still gets pretty much all of the attention currently, and "developers" complain and talk down on it with negativity just because it hasn't been updated in a long time (rather than actually try to do something about it as a developer), my fork on the other hand hardly has/gets any attention mostly because there're hardly any people making Lua scripts anymore (and the existing ones link to your version) and I haven't really released many Lua scripts myself to draw attention to it.

Also, sure, I wouldn't mind having ownership of the GitHub repos, thanks. My only issue pretty much has been with the core, the ASI; the source for the ASI doesn't compile even when I try to provide the missing required files for it (like the natives file), but, I still probably/likely wouldn't be able to do anything due to my lack of knowledge to update the ASI with the much needed features such as the ability to more directly invoke natives through Lua, so pretty much every change/update that I've done is just via what is possible/doable from the Lua environment side of things, including a function remapper that provides more up to date names to the exposed native calling functions (though it doesn't fix the other issue of natives that had their param definitions changed which renders them completely unusable because you can't supply the "wrong" type to those functions).

But yeah, I've been trying my best, learning a lot more over time and doing my best to make it into something modern that is really nice to work with especially for people who are new to scripting/modding and especially to Lua, I'm just hindered because I don't know how to update the core/ASI lol.

**Comment by JayMontana36** [comment]
Hey @gallexme so I've been reading up a bit more, do you still happen to have the automatic build things (complete) around anywhere? I would like to try to use that to build/generate newer ASIs with newer RAGE native definitions and so on for now.

**Comment by gallexme** [comment]
@JayMontana36 hey i just got smth to plug my old hdd's into

i found the the automation thing!
https://mega.nz/file/KI9nXQ6I#Vs8EXUgWPpilSMvPZTJgv3zE6o1q3xPLZQX7n_rD3Bw

enjoy!(also contains some unreleased code :) hope that helps you, if it doesnt please report back i may would give it a go for a few hours even tho i dont play gta5 anymore

**Comment by JayMontana36** [comment]
Thanks, sorry I've been kinda busy; I downloaded and tried it a few hours ago, downloaded and installed Visual Studio 2015 (previously had 2019 but that was complaining about a lot more (compatibility/legacy) with no fixes), and got to the point where I managed to get rid of the errors that 2019 gave me that 2015 also gave me (because it was still newer, different compiler or whatever), but then after I still can't get the source version from the automation files to compile, and trying to compile the last source version on GitHub (getting rid of the same aforementioned errors and then copying in the missing/required files from the automation version that it asked for) also has the same thing.

Pretty much either way I just get '`argument of type "unsigned long *" is incompatible with parameter of type "int *"`' throughout over and over, or something similar with floats and maybe others; I'm not exactly sure how it all works.

LPC1

**Pull request closed without merging**
